version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:{{KC_TAG}}
    environment:
      KC_HOSTNAME: {{KC_HOSTNAME}}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_PROXY: edge
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db/postgres
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - {{KC_HOST_PORT}}:8080
    command: ["start"]
  db:
    image: postgres:{{POSTGRES_TAG}}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
